sudo: required
dist: xenial
language: minimal

services:
- docker

git:
  submodules: false

before_install:
- travis_wait git submodule update --init --recursive

install:
- docker build .

script:
- while sleep 8m; do echo "=====[ $SECONDS seconds, heartbeat to prevent Travis timing out ]====="; done &
- bash quick-start.sh generic
- kill %1

branches:
  only:
  - master
  - wip
  except:
  - master
  - wip
